### ISSUE TITLE
This was not approved by @njhartwell

### ISSUE THREAD

**Issue by fidian** [tests-always-included/mr-fusion#2]
Desperately seeking @njhartwell's feedback.

**Comment by njhartwell** [comment]
Looks good to me! We might have to try it for our main application repo.

**Comment by fidian** [comment]
:-)  It's a little rough and untested at the moment.  How about waiting a few days and let me close #1 by writing tests before you start using this with production code?

However, I did get feedback, so I'm closing this issue.
